In [1]:
#Install pyspark[sql] to access pyarrow
!pip install pyspark[sql]

Requirement already satisfied: pyspark[sql] in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (2.4.8)
Requirement already satisfied: py4j==0.10.7 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pyspark[sql]) (0.10.7)
Collecting pyarrow>=0.8.0
  Downloading pyarrow-10.0.0-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (35.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.4/35.4 MB 27.9 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: pandas>=0.19.2 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pyspark[sql]) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.19.2->pyspark[sql]) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.19.2->pyspark[sql]) (2022.5)
Requirement already satisfied: numpy>=1.17.3 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from pandas>=0.19.2->pyspark[sql]) (1.21.6)
Requirement already satisfied: six>=1.5 in /home/jupyterlab/conda/envs/python/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->pyspark[sql]) (1.16.0)
Installing collected packages: pyarrow
Successfully installed pyarrow-10.0.0

In [3]:
#Read in the parquet file to a pandas dataframe
import pandas as pd
pd.read_parquet('data.parquet', engine='pyarrow')

,x,y,z,source,class
0,33,36,51,Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt,Eat_meat
1,33,36,51,Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt,Eat_meat
2,33,35,53,Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt,Eat_meat
3,31,37,52,Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt,Eat_meat
4,32,36,52,Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt,Eat_meat
...,...,...,...,...,...
329682,25,45,46,Accelerometer-2011-05-30-10-21-50-sitdown_chai...,Sitdown_chair
329683,24,45,47,Accelerometer-2011-05-30-10-21-50-sitdown_chai...,Sitdown_chair
329684,24,45,47,Accelerometer-2011-05-30-10-21-50-sitdown_chai...,Sitdown_chair
329685,25,47,46,Accelerometer-2011-05-30-10-21-50-sitdown_chai...,Sitdown_chair
329686,25,46,46,Accelerometer-2011-05-30-10-21-50-sitdown_chai...,Sitdown_chair

In [10]:
#Convert the parquet file to CSV format
import dask.dataframe as dd

ddf = dd.read_parquet('data.parquet')

ddf.to_csv("data_transform.csv", 
           single_file=True, 
           index=False
)

    x   y   z                                             source     class
0  33  36  51  Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt  Eat_meat
1  33  36  51  Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt  Eat_meat
2  33  35  53  Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt  Eat_meat
3  31  37  52  Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt  Eat_meat
4  32  36  52  Accelerometer-2011-03-24-13-21-39-eat_meat-f1.txt  Eat_meat

In [ ]:
#Create a 80-20 training and test split with seed=1
splits = df.randomSplit([0.8, 0.2], seed=1)
df_train = splits[0]
df_test = splits[1]

In [ ]:
#Train a Random Forest model with different hyperparameters listed below and report the best performing hyperparameter combinations.
rf=RandomForestClassifier(numTrees=curNTrees,maxDepth=curMaxDepth,seed=1)

number of trees : {10, 20}   - maximum depth : {5, 7} 


for curNTrees in [10, 20]:
    for curMaxDepth in [5, 7]:
         rf=RandomForestClassifier(numTrees=curNTrees,maxDepth=curMaxDepth,seed=1)